apiVersion: v1
kind: Service
metadata:
  name: {{ template "sgm-optimization-service.fullname" . }}
  labels:
    {{- include "sgm-optimization-service.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
{{ include "sgm-optimization-service.servicePorts" . | indent 4 -}}
  type: {{ default "ClusterIP" .Values.serviceType }}
